/**
 * Deterministic integer hashing — the TypeScript half of a contract shared with
 * the fragment shader (see `hashCell`/`uhash` in raymarch.frag.glsl).
 *
 * WHY INTEGER HASHING (not `fract(sin(...))`): procedural content — building
 * footprints, window lights, and (Milestone 3) obstacle placement — is generated
 * independently on the GPU (for rendering) and the CPU (for game logic). Those two
 * evaluations MUST agree bit-for-bit, or a car will collide with a building the
 * player cannot see. Float `sin` hashing drifts between the GLSL and JS math
 * libraries; a pure integer bit-mixer is identical on both because it uses only
 * 32-bit wrapping multiply/xor/shift, which both platforms define exactly.
 *
 * DETERMINISM CONTRACT: this file and raymarch.frag.glsl implement the same two
 * functions. Any change here must be mirrored there and vice versa. The
 * reference values in the assertion block below are produced by these exact ops;
 * the GLSL side must hash the same cell coordinates to the same 32-bit words.
 *
 * `Math.imul` gives a true 32-bit wrapping multiply (matching GLSL `uint *`);
 * `>>> 0` and `>>>` keep values in the unsigned 32-bit domain (matching GLSL
 * `uint` and its logical `>>`). XOR is bit-identical on both platforms.
 */

/** lowbias32 integer bit-finalizer (Chris Wellons). Excellent avalanche, cheap. */
export function uhash(x: number): number {
  x = x >>> 0;
  x ^= x >>> 16;
  x = Math.imul(x, 0x7feb352d);
  x ^= x >>> 15;
  x = Math.imul(x, 0x846ca68b);
  x ^= x >>> 16;
  return x >>> 0;
}

/**
 * Hash a 3D integer cell coordinate to a 32-bit seed. Odd multiplier constants
 * decorrelate the three axes before mixing so neighbouring cells look unrelated.
 * Negative coordinates wrap into the unsigned domain identically to GLSL's
 * `uint(int)` cast, so cells behind the origin (z < 0) hash consistently.
 */
export function hashCell(cx: number, cy: number, cz: number): number {
  let h = uhash(Math.imul(cx, 0x9e3779b9));
  h = uhash(h ^ Math.imul(cy, 0x85ebca6b));
  h = uhash(h ^ Math.imul(cz, 0xc2b2ae35));
  return h >>> 0;
}

/** Map a hashed word to a float in [0, 1). Uses the top 24 bits so the result
 *  survives conversion through a 32-bit float mantissa on the GPU unchanged. */
export function hashToFloat(h: number): number {
  return (h >>> 8) / 16777216;
}

// --- Determinism self-check (paired with the same inputs in the shader) ------
// If the bit-mixer is ever altered, this throws at module load. The GLSL side
// hashes these same cells to the same 32-bit words; keeping the reference values
// here documents the contract and catches accidental drift on the CPU side.
// Reference words were generated by these exact functions under Node.
//   uhash(1)          -> 0x688990c0
//   hashCell(1, 0,-3) -> 0xab5f112a   hashCell(-1, 1, 7) -> 0x09cbf7c3
if (
  uhash(1) !== 0x688990c0 ||
  hashCell(1, 0, -3) !== 0xab5f112a ||
  hashCell(-1, 1, 7) !== 0x09cbf7c3
) {
  throw new Error('hash.ts determinism contract broken — sync with raymarch.frag.glsl');
}
